config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :stores do
    resources :products, only: [:index, :create, :update, :destroy] do
      member do
        patch 'enable'
        patch 'disable'
      end
    end

    get "/orders/new" => "stores#new_order"
  end
  
  get 'welcome/index'
  get "listing" => "products#listing"
  get "me" => "registrations#me"
  get "user_listing" => "registrations#user_listing", as: :user_listing
  get 'orders/new', to: 'orders#new', as: 'new_order'

  
  post "new" => "registrations#create", as: :create_registration
  post "sign_in" => "registrations#sign_in"
  
  scope :buyers do
    resources :orders, only: [:index, :create, :update, :destroy]
  end

  resources :registrations, only: [:index] do
    member do
      patch :change_role
    end
  end

  resources :stores do
    member do
      patch :disable_user
    end
  end

  resources :carts, only: [:show] do
    collection do
      post :add_item
      delete :remove_item
      post :checkout
    end
  end

  resources :orders, only: [:create, :index, :show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  root to: "welcome#index"
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
  before_validation :ensure_seller
  validates :name, presence: true, length: { minimum: 3 }

  private

  def ensure_seller
    self.user = nil if self.user && !self.user.seller?
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  include ActionController::Live

  skip_forgery_protection only: %i[create update]
  before_action :authenticate!
  before_action :set_store, only: %i[ show edit update destroy ]
  rescue_from User::InvalidToken, with: :not_authorized

  def index
    @stores = if current_user.seller?
                Store.where(user: current_user)
              else
                Store.joins(:user).where(users: { role: 'seller' })
              end
  end

  # GET /stores/1 or /stores/1.json
  def show
    @store = Store.find(params[:id])
    @products = @store.products.page(params[:page]).per(8)
  end

  # GET /stores/new
  def new
    @store = Store.new
    if current_user.admin?
      @sellers = User.where(role: :seller)
    end
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)
    if !current_user.admin?
      @store.user = current_user
    end

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_order
    response.headers["Content-Type"] = "text/event-stream"
    sse = SSE.new(response.stream, retry: 300, event: "waiting-orders")

    EventMachine.run do
      EventMachine::PeriodicTimer.new(3) do
        order = Order.last
        if order
          message = { time: Time.now, order: order }
          sse.write(message, event: "new-order")
        else
          sse.write({ message: "No new orders" }, event: "no-order")
        end
      end
    end
  rescue IOError, ActionController::Live::ClientDisconnected
    sse.close
  ensure
    sse.close
  end


  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    required = params.require(:store)
    if current_user.admin?
      required.permit(:name, :user_id)
    else
      required.permit(:name)
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %><br/>
  </div>

  <% if current_user.admin? %>
  <div>
    <%= form.label :seller, style: "display: block" %>
    <%= form.collection_select :user_id, @sellers, :id, :email, prompt: "Sellers..." %>
  </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<div id="<%= dom_id store %>">
  <p>
    <strong>Name:</strong>
    <%= store.name %>
  </p>

</div>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render "form", store: @store %>

<br>
<%= link_to 'Disable My Account', disable_user_store_path(@store),
            method: :patch,
            data: { confirm: 'Are you sure you want to disable your account?' },
            class: 'btn btn-warning' %>

                  
<div>
  <%= link_to "Show this store", @store %> |
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stores</h1>

<div id="stores">
  <% @stores.each do |store| %>
    <%= render store %>
    <p>
      <%= link_to "Show this store", store %>
    </p>
  <% end %>
</div>

<%= link_to "New store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render "form", store: @store %>

<br>

<div>
  <%= link_to "Back to stores", stores_path %>
</div>

app/views/stores/show.html.erb
<p class="notice"><%= notice %></p>

<%= render @store %>

<h2>Products</h2>
<div class="products">
  <% @products.each do |product| %>
    <div class="product">
      <p><strong>Title:</strong> <%= product.title %></p>
      <p><strong>Price:</strong> <%= number_to_currency(product.price) %></p>
      <%= form_with url: add_item_cart_path(product_id: product.id), method: :post do |form| %>
        <%= form.label :quantity %>
        <%= form.number_field :quantity, value: 1, min: 1 %>
        <%= form.submit 'Add to Cart' %>
      <% end %>
    </div>
  <% end %>
</div>

<%# <div class="pagination"> %>
 <%# <%= paginate @products, theme: 'custom' %>
<%# </div> %>

<hr class="separator" />
<br/>

<div class="store-links">
  <%= link_to "Edit this store", edit_store_path(@store), class: "edit-link" %> |
  <%= link_to "Back to stores", stores_path, class: "back-link" %>

  <%= button_to "Destroy this store", @store, method: :delete, class: "destroy-button" %>
</div>