config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :stores do
    resources :products, only: [:index, :create, :update, :destroy] do
      member do
        patch 'enable'
        patch 'disable'
      end
    end

    get "/orders/new" => "stores#new_order"
  end
  
  get 'welcome/index'
  get "listing" => "products#listing"
  get "me" => "registrations#me"
  get "user_listing" => "registrations#user_listing", as: :user_listing
  get 'orders/new', to: 'orders#new', as: 'new_order'

  
  post "new" => "registrations#create", as: :create_registration
  post "sign_in" => "registrations#sign_in"
  
  scope :buyers do
    resources :orders, only: [:index, :create, :update, :destroy]
  end

  resources :registrations, only: [:index] do
    member do
      patch :change_role
    end
  end

  resources :stores do
    member do
      patch :disable_user
    end
  end

  resources :carts, only: [:show] do
    collection do
      post :add_item
      delete :remove_item
      post :checkout
    end
  end

  resources :orders, only: [:create, :index, :show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  root to: "welcome#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome to Delivery!</h1>

<p style="color: green"><%= notice %>

<% if current_user %>
  <p>Logged in as <strong><%= current_user.email %></strong></p><br/>
  <%= button_to "Go to Stores", stores_path, method: :get %><br/>

  <% if current_user.admin? %>
    <%= button_to "User List", user_listing_path, method: :get %><br/>
  <% end %>
  
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  or
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>